{% set version = "2.0.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-argparse
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/argparse_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/argparse/argparse_{{ version }}.tar.gz
  sha256: d26139c610ea0adf8d6632699cd34c4595ae3e7963bfc7a00cb3b7504f2059b0

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-findpython
    - r-getopt >=1.19
    - r-jsonlite
  run:
    - r-base
    - r-r6
    - r-findpython
    - r-getopt >=1.19
    - r-jsonlite

test:
  commands:
    - $R -e "library('argparse')"           # [not win]
    - "\"%R%\" -e \"library('argparse')\""  # [win]

about:
  home: https://github.com/trevorld/r-argparse
  license: GPL (>= 2)
  summary: A command line parser to be used with Rscript to write "#!" shebang scripts that gracefully accept positional and optional arguments and automatically generate usage.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: argparse
# Type: Package
# Title: Command Line Optional and Positional Argument Parser
# Version: 2.0.0
# Authors@R: c(person("Trevor L", "Davis", role=c("aut", "cre"), email="trevor.l.davis@gmail.com"), person("Allen", "Day", role="ctb", comment="Some documentation and examples ported from the getopt package."), person("Python Software Foundation", role="ctb", comment="Some documentation from the optparse Python module."), person("Paul", "Newell", role="ctb"))
# Description: A command line parser to be used with Rscript to write "#!" shebang scripts that gracefully accept positional and optional arguments and automatically generate usage.
# License: GPL (>= 2)
# Copyright: See file (inst/)COPYRIGHTS.
# URL: https://github.com/trevorld/r-argparse
# BugReports: https://github.com/trevorld/r-argparse/issues
# LazyLoad: yes
# Imports: R6, findpython, getopt (>= 1.19), jsonlite
# SystemRequirements: python (>= 3.2)
# Suggests: knitr (>= 1.15.19), testthat
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2018-11-30 21:38:08 UTC; trevorld
# Author: Trevor L Davis [aut, cre], Allen Day [ctb] (Some documentation and examples ported from the getopt package.), Python Software Foundation [ctb] (Some documentation from the optparse Python module.), Paul Newell [ctb]
# Maintainer: Trevor L Davis <trevor.l.davis@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-11-30 23:00:03 UTC
