{% set version = '2.0.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-argparse
  version: {{ version|replace("-", "_") }}

source:
  fn: argparse_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/argparse_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/argparse/argparse_{{ version }}.tar.gz
  sha256: 71fcac2b3070294e7e9714f5d5c38bdaaa621055e668fe01f7d9548d183c37e3

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-findpython
    - r-jsonlite
    - r-r6

  run:
    - r-base
    - r-findpython
    - r-jsonlite
    - r-r6
    - python

test:
  commands:
    - $R -e "library('argparse')"  # [not win]
    - "\"%R%\" -e \"library('argparse')\""  # [win]

about:
  home: https://github.com/trevorld/argparse
  license: GPL (>= 2)
  summary: A command line parser to be used with Rscript to write "#!" shebang scripts that gracefully
    accept positional and optional arguments and automatically generate usage.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
