appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: tBjSUKz3EKO04RwYi4/jniS5V03IP4gmkHP9t1dnFmQOdApbGUFD6W+PSJGx9Znb9njYoV2khjFoDu+hjxJ7oU3YX/HbKnRpiDi8IeysEWmasnlwFsKQxYXXS+z5dTi3kObbfP7W+0TfNLmAWXXV78NRhaysueA/9nBxseCrGVTm8wdDzRoCHl9yz0E92L9DnA4O2s7OcYlNoQYABCMPGkELKtVZSSrj2ELA5xnE48t3rPCkKS1rL3gjgYooWC6Jc2Icdal/BxMRxwhOQWIHmQJ7ya0GOnwVuJ1yz5d53Vgv9/3F5M0FNQo/j509kyxBHgjkKcNRbq5butJxIcuQ6xPndrTUZM3SXbj6qxHwvZc/UWSwdH3GFAZX/Lw7paW6NdGHXWsgRLaBIZODGVYgKCADn0xJGHeYTE8udAm+T/ztVH24lsHvSrxse5/Dk3z9TSGZPcgG63mbkXof11InAZP8Rlo/kADvIFwH0iLnxLlA19QTKDYQ0mL7MTGNjTavJ2Uyv4ZVPiPfpG+wy59oV2TCBICtaCjH+2H0nve9eSjRFG+TMNwOWBQdOkwqbVPgFr9K+Njhzb9srOq1MUMupU/qYCyS3VIXlwR6bKsAT0mmff6vCBfC052YS7euy+Qv74aPm9gElleY0mqjrj96VWaVD2WjfmP3j7l+vq8m00k=
